const SET_CUSTOMER_COUNT = 'SET_CUSTOMER_COUNT'
const SET_REALTOR_COUNT = 'SET_REALTORS_COUNT'
const SET_CUSTOMERS = 'SET_CUSTOMERS'
const SET_CUSTOMER = 'SET_CUSTOMER'
export { SET_CUSTOMER_COUNT, SET_REALTOR_COUNT, SET_CUSTOMERS, SET_CUSTOMER }
