const SET_PRODUCTS = 'SET_PRODUCTS'
const SET_PRODUCT = 'SET_PRODUCT'
const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION'
const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS'
const SET_SUBSCRIPTIONS_COUNT = 'SET_SUBSCRIPTIONS_COUNT'
const SET_PRODUCT_SOLD = 'SET_PRODUCT_SOLD'
export {
  SET_PRODUCTS,
  SET_PRODUCT,
  SET_SUBSCRIPTION,
  SET_SUBSCRIPTIONS,
  SET_SUBSCRIPTIONS_COUNT,
  SET_PRODUCT_SOLD,
}
