const SET_PRODUCTS = 'SET_PRODUCTS'
const SET_PRODUCT = 'SET_PRODUCT'
const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION'
const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS'
export { SET_PRODUCTS, SET_PRODUCT, SET_SUBSCRIPTION, SET_SUBSCRIPTIONS }
