const SET_TRANSACTIONS = 'SET_TRANSACTIONS'
const SET_TRANSACTION = 'SET_TRANSACTION'
const SET_PRODUCTS_COMMISSION = 'SET_PRODUCTS_COMMISSION'
export { SET_TRANSACTIONS, SET_TRANSACTION, SET_PRODUCTS_COMMISSION }
